menu for mobile
line64/landricks-components pull request #13
Opened 2017-01-31 20:15 UTC by manueloteroeiras

It's just like the old **NavigationBrick**, but now the component should receive a new prop called `mobile` (it's opcional).

For example:
```
 <NavigationBrick
       mode="FIXED"
       logo={ require('../images/logo.svg') }
       items={[
         { label: "why", onClick: () => this.navigateToSection('why') },
         { label: "how", onClick: () => this.navigateToSection('how') },
       ]}
       theme={ navigation }
       mobile={ (this.getWidth() < 500) ? true : false }       
/>
```

2017-01-31 20:33 UTC, scarmuega requested changes
We already have the "viewport" prop that is injected by the LandingCanvas. NavigationBrick should use that prop to decide how to render things.

2017-02-01 18:38 UTC, manueloteroeiras commented
@scarmuega check it now, NavigationBrick renders fullwidthscreen or collapsed regarding the viewport prop.
The collapsed mode is for `xs` and `sm` screens and the fullWidth for `md` and `lg`.

2017-02-01 18:38 UTC, scarmuega requested changes

2017-02-01 18:38 UTC, scarmuega commented on src/components/NavigationBrick/index.js
> +						<a style={ s.itemLink } href="#" onClick={ this.handleClick(item.onClick) }>{ item.label }</a>
If item contains an onClick handler, render a <button/>
if item contains an href string, render an <a/>

2017-02-01 18:38 UTC, scarmuega commented on src/components/NavigationBrick/index.js
> +	handleClick(onClick, args) {
you don't need this method, just call the onClick handler when you render the <button/>

2017-02-01 18:38 UTC, scarmuega commented on src/components/NavigationBrick/index.js
> +		if (items && items.length > 0) {
un-nest the conditionals. use... `if (!items || items.length) return null;`

2017-02-01 18:38 UTC, scarmuega commented on src/components/NavigationBrick/styles.js
> +    mobile: {
call this prop "collapsed" so that it matches render naming conventions

2017-02-01 18:38 UTC, scarmuega commented on src/components/NavigationBrick/styles.js
>    if (mode === 'FIXED') {
what is the "mode" prop for?

2017-02-02 14:43 UTC, manueloteroeiras commented
@scarmuega recently I have pushed new changes.

2017-02-06 21:08 UTC, manueloteroeiras commented
@scarmuega  Hi there, I pushed new changes for NavigationBrick. I change the variable `s` to styles. And rename styles file to styler.

2017-02-07 20:41 UTC, merged